-- RFID attendance database for the administrator, teacher, and student roles.
-- Passwords intentionally live only in Supabase Auth (auth.users).

create type public.user_role as enum ('admin', 'teacher', 'student');
create type public.account_status as enum ('active', 'inactive', 'archived');
create type public.rfid_card_status as enum ('Active', 'Inactive', 'Lost', 'Deactivated');
create type public.attendance_status as enum ('Present', 'Late', 'Absent', 'Excused');
create type public.sms_status as enum ('Pending', 'Sent', 'Failed');

create table public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  role public.user_role not null default 'student',
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_email_not_blank check (btrim(email) <> '')
);

create unique index users_email_unique_idx on public.users (lower(email));

comment on table public.users is
  'Application role and account state. Authentication credentials are managed by Supabase Auth.';

create table public.courses (
  id bigint generated by default as identity primary key,
  department text not null,
  course_name text not null,
  created_at timestamptz not null default now(),
  constraint courses_department_not_blank check (btrim(department) <> ''),
  constraint courses_name_not_blank check (btrim(course_name) <> ''),
  constraint courses_department_name_unique unique (department, course_name)
);

create table public.students (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users (id) on delete cascade,
  student_id text not null unique,
  full_name text not null,
  profile_picture text,
  gender text,
  date_of_birth date,
  place_of_birth text,
  address text,
  contact_number text,
  email text not null,
  parent_name text not null,
  parent_contact_number text not null,
  year_level text not null,
  section text not null,
  course text not null,
  campus text not null,
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint students_student_id_not_blank check (btrim(student_id) <> ''),
  constraint students_full_name_not_blank check (btrim(full_name) <> ''),
  constraint students_email_not_blank check (btrim(email) <> ''),
  constraint students_parent_name_not_blank check (btrim(parent_name) <> ''),
  constraint students_parent_contact_not_blank check (btrim(parent_contact_number) <> ''),
  constraint students_year_level_not_blank check (btrim(year_level) <> ''),
  constraint students_section_not_blank check (btrim(section) <> ''),
  constraint students_course_not_blank check (btrim(course) <> ''),
  constraint students_campus_not_blank check (btrim(campus) <> '')
);

create unique index students_email_unique_idx on public.students (lower(email));
create index students_academic_placement_idx
  on public.students (campus, course, year_level, section);

create table public.teachers (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.users (id) on delete cascade,
  teacher_id text not null unique,
  full_name text not null,
  profile_picture text,
  gender text,
  date_of_birth date,
  civil_status text,
  email text not null,
  phone_number text,
  department text not null,
  course text not null,
  date_hired date,
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teachers_teacher_id_not_blank check (btrim(teacher_id) <> ''),
  constraint teachers_full_name_not_blank check (btrim(full_name) <> ''),
  constraint teachers_email_not_blank check (btrim(email) <> ''),
  constraint teachers_department_not_blank check (btrim(department) <> ''),
  constraint teachers_course_not_blank check (btrim(course) <> '')
);

create unique index teachers_email_unique_idx on public.teachers (lower(email));
create index teachers_department_course_idx on public.teachers (department, course);

create table public.rfid_cards (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  rfid_number text not null unique,
  card_status public.rfid_card_status not null default 'Active',
  assigned_date date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint rfid_cards_number_not_blank check (btrim(rfid_number) <> ''),
  constraint rfid_cards_id_student_unique unique (id, student_id)
);

-- A student can retain old cards for audit history, but only one can be active.
create unique index rfid_cards_one_active_per_student_idx
  on public.rfid_cards (student_id)
  where card_status = 'Active';
create index rfid_cards_student_idx on public.rfid_cards (student_id);

create table public.attendance_records (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  rfid_card_id bigint not null,
  attendance_date date not null default current_date,
  time_in time not null,
  time_out time,
  attendance_status public.attendance_status not null default 'Present',
  campus text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attendance_card_belongs_to_student_fk
    foreign key (rfid_card_id, student_id)
    references public.rfid_cards (id, student_id),
  constraint attendance_one_record_per_student_day
    unique (student_id, attendance_date),
  constraint attendance_campus_not_blank check (btrim(campus) <> ''),
  constraint attendance_time_order check (time_out is null or time_out >= time_in),
  constraint attendance_id_student_unique unique (id, student_id)
);

create index attendance_records_date_idx
  on public.attendance_records (attendance_date desc);
create index attendance_records_card_idx
  on public.attendance_records (rfid_card_id);

create table public.sms_notifications (
  id bigint generated by default as identity primary key,
  attendance_id bigint not null,
  student_id bigint not null references public.students (id) on delete cascade,
  parent_contact_number text not null,
  message text not null,
  sms_status public.sms_status not null default 'Pending',
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  constraint sms_attendance_belongs_to_student_fk
    foreign key (attendance_id, student_id)
    references public.attendance_records (id, student_id)
    on delete cascade,
  constraint sms_parent_contact_not_blank check (btrim(parent_contact_number) <> ''),
  constraint sms_message_not_blank check (btrim(message) <> ''),
  constraint sms_sent_timestamp_consistent check (
    (sms_status = 'Sent' and sent_at is not null)
    or (sms_status <> 'Sent')
  )
);

create index sms_notifications_attendance_idx
  on public.sms_notifications (attendance_id);
create index sms_notifications_student_created_idx
  on public.sms_notifications (student_id, created_at desc);
create index sms_notifications_status_idx
  on public.sms_notifications (sms_status)
  where sms_status <> 'Sent';

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger users_set_updated_at
before update on public.users
for each row execute function public.set_updated_at();

create trigger students_set_updated_at
before update on public.students
for each row execute function public.set_updated_at();

create trigger teachers_set_updated_at
before update on public.teachers
for each row execute function public.set_updated_at();

create trigger rfid_cards_set_updated_at
before update on public.rfid_cards
for each row execute function public.set_updated_at();

create trigger attendance_records_set_updated_at
before update on public.attendance_records
for each row execute function public.set_updated_at();

-- Keep the public role row synchronized with Supabase Auth accounts.
create or replace function public.handle_auth_user_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_role public.user_role;
begin
  requested_role := case
    when new.raw_app_meta_data ->> 'role' in ('admin', 'teacher', 'student')
      then (new.raw_app_meta_data ->> 'role')::public.user_role
    else 'student'::public.user_role
  end;

  insert into public.users (id, email, role)
  values (new.id, coalesce(new.email, ''), requested_role)
  on conflict (id) do update
    set email = excluded.email,
        role = excluded.role;

  return new;
end;
$$;

create trigger on_auth_user_change
after insert or update of email, raw_app_meta_data on auth.users
for each row execute function public.handle_auth_user_change();

insert into public.users (id, email, role)
select
  id,
  coalesce(email, ''),
  case
    when raw_app_meta_data ->> 'role' in ('admin', 'teacher', 'student')
      then (raw_app_meta_data ->> 'role')::public.user_role
    else 'student'::public.user_role
  end
from auth.users
where email is not null
on conflict (id) do nothing;

-- Security-definer helpers avoid recursive users-table RLS checks.
create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role from public.users where id = auth.uid()
$$;

create or replace function public.current_student_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select id from public.students where user_id = auth.uid()
$$;

revoke all on function public.current_user_role() from public;
revoke all on function public.current_student_id() from public;
grant execute on function public.current_user_role() to authenticated;
grant execute on function public.current_student_id() to authenticated;

alter table public.users enable row level security;
alter table public.students enable row level security;
alter table public.teachers enable row level security;
alter table public.rfid_cards enable row level security;
alter table public.attendance_records enable row level security;
alter table public.sms_notifications enable row level security;
alter table public.courses enable row level security;

create policy users_read_own
on public.users for select to authenticated
using (id = auth.uid());

create policy users_admin_all
on public.users for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy students_read_by_role
on public.students for select to authenticated
using (
  user_id = auth.uid()
  or public.current_user_role() in ('admin', 'teacher')
);

create policy students_admin_write
on public.students for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy teachers_read_by_role
on public.teachers for select to authenticated
using (
  user_id = auth.uid()
  or public.current_user_role() = 'admin'
);

create policy teachers_admin_write
on public.teachers for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy rfid_cards_read_by_role
on public.rfid_cards for select to authenticated
using (
  student_id = public.current_student_id()
  or public.current_user_role() in ('admin', 'teacher')
);

create policy rfid_cards_admin_write
on public.rfid_cards for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy attendance_read_by_role
on public.attendance_records for select to authenticated
using (
  student_id = public.current_student_id()
  or public.current_user_role() in ('admin', 'teacher')
);

create policy attendance_admin_write
on public.attendance_records for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy sms_read_by_owner_or_admin
on public.sms_notifications for select to authenticated
using (
  student_id = public.current_student_id()
  or public.current_user_role() = 'admin'
);

create policy sms_admin_write
on public.sms_notifications for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy courses_authenticated_read
on public.courses for select to authenticated
using (true);

create policy courses_admin_write
on public.courses for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

grant usage on schema public to authenticated;
grant select on public.users, public.students, public.teachers,
  public.rfid_cards, public.attendance_records, public.sms_notifications,
  public.courses to authenticated;
grant insert, update, delete on public.users, public.students, public.teachers,
  public.rfid_cards, public.attendance_records, public.sms_notifications,
  public.courses to authenticated;
grant usage, select on all sequences in schema public to authenticated;

