-- Clarify academic terminology:
--   program = degree program (BSIT, BSHM)
--   course  = subject (IPT, ITE, MS101)
-- A teacher can have multiple program/course/year-level/section assignments.

create table public.programs (
  id bigint generated by default as identity primary key,
  program_code text not null,
  program_name text not null,
  department text,
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint programs_code_not_blank check (btrim(program_code) <> ''),
  constraint programs_name_not_blank check (btrim(program_name) <> '')
);

create unique index programs_code_unique_idx
  on public.programs (upper(program_code));

-- Preserve values from the original schema before replacing ambiguous columns.
insert into public.programs (program_code, program_name)
select source.program_code, source.program_code
from (
  select distinct btrim(department) as program_code from public.courses
  union
  select distinct btrim(course) as program_code from public.students
  union
  select distinct btrim(department) as program_code from public.teachers
) as source
where source.program_code <> ''
on conflict do nothing;

alter table public.courses
  add column program_id bigint,
  add column course_code text,
  add column updated_at timestamptz not null default now();

update public.courses as course
set
  program_id = program.id,
  course_code = course.course_name
from public.programs as program
where upper(program.program_code) = upper(course.department);

alter table public.courses
  alter column program_id set not null,
  alter column course_code set not null,
  add constraint courses_program_fk
    foreign key (program_id) references public.programs (id),
  add constraint courses_code_not_blank check (btrim(course_code) <> ''),
  add constraint courses_id_program_unique unique (id, program_id);

alter table public.courses
  drop constraint courses_department_name_unique,
  drop constraint courses_department_not_blank,
  drop column department;

create unique index courses_program_code_unique_idx
  on public.courses (program_id, upper(course_code));
create index courses_program_idx on public.courses (program_id);

-- Include teacher subjects that were not already present in the course catalog.
insert into public.courses (program_id, course_code, course_name)
select distinct program.id, btrim(teacher.course), btrim(teacher.course)
from public.teachers as teacher
join public.programs as program
  on upper(program.program_code) = upper(teacher.department)
where btrim(teacher.course) <> ''
on conflict do nothing;

drop index public.students_academic_placement_idx;

alter table public.students add column program_id bigint;

update public.students as student
set program_id = program.id
from public.programs as program
where upper(program.program_code) = upper(student.course);

alter table public.students
  alter column program_id set not null,
  add constraint students_program_fk
    foreign key (program_id) references public.programs (id),
  drop constraint students_course_not_blank,
  drop column course;

create index students_academic_placement_idx
  on public.students (campus, program_id, year_level, section);

create table public.teacher_assignments (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers (id) on delete cascade,
  program_id bigint not null references public.programs (id),
  course_id bigint not null,
  year_level text,
  section text,
  campus text,
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teacher_assignments_course_program_fk
    foreign key (course_id, program_id)
    references public.courses (id, program_id),
  constraint teacher_assignments_year_level_not_blank
    check (year_level is null or btrim(year_level) <> ''),
  constraint teacher_assignments_section_not_blank
    check (section is null or btrim(section) <> ''),
  constraint teacher_assignments_campus_not_blank
    check (campus is null or btrim(campus) <> ''),
  constraint teacher_assignments_unique
    unique nulls not distinct
      (teacher_id, course_id, year_level, section, campus)
);

insert into public.teacher_assignments (teacher_id, program_id, course_id)
select teacher.id, program.id, course.id
from public.teachers as teacher
join public.programs as program
  on upper(program.program_code) = upper(teacher.department)
join public.courses as course
  on course.program_id = program.id
 and upper(course.course_code) = upper(teacher.course)
on conflict do nothing;

drop index public.teachers_department_course_idx;

alter table public.teachers
  drop constraint teachers_course_not_blank,
  drop column course;

create index teacher_assignments_teacher_idx
  on public.teacher_assignments (teacher_id);
create index teacher_assignments_class_idx
  on public.teacher_assignments (program_id, year_level, section);
create index teacher_assignments_course_idx
  on public.teacher_assignments (course_id);

create trigger programs_set_updated_at
before update on public.programs
for each row execute function public.set_updated_at();

create trigger courses_set_updated_at
before update on public.courses
for each row execute function public.set_updated_at();

create trigger teacher_assignments_set_updated_at
before update on public.teacher_assignments
for each row execute function public.set_updated_at();

create or replace function public.teacher_can_access_student(target_student_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.students as student
    join public.teacher_assignments as assignment
      on assignment.program_id = student.program_id
     and (assignment.year_level is null or assignment.year_level = student.year_level)
     and (assignment.section is null or assignment.section = student.section)
     and (assignment.campus is null or assignment.campus = student.campus)
    join public.teachers as teacher on teacher.id = assignment.teacher_id
    where student.id = target_student_id
      and teacher.user_id = auth.uid()
      and student.status = 'active'
      and teacher.status = 'active'
      and assignment.status = 'active'
  )
$$;

revoke all on function public.teacher_can_access_student(bigint) from public;
grant execute on function public.teacher_can_access_student(bigint) to authenticated;

alter table public.programs enable row level security;
alter table public.teacher_assignments enable row level security;

drop policy students_read_by_role on public.students;
create policy students_read_by_role
on public.students for select to authenticated
using (
  user_id = auth.uid()
  or public.current_user_role() = 'admin'
  or public.teacher_can_access_student(id)
);

drop policy rfid_cards_read_by_role on public.rfid_cards;
create policy rfid_cards_read_by_role
on public.rfid_cards for select to authenticated
using (
  student_id = public.current_student_id()
  or public.current_user_role() = 'admin'
  or public.teacher_can_access_student(student_id)
);

drop policy attendance_read_by_role on public.attendance_records;
create policy attendance_read_by_role
on public.attendance_records for select to authenticated
using (
  student_id = public.current_student_id()
  or public.current_user_role() = 'admin'
  or public.teacher_can_access_student(student_id)
);

create policy programs_authenticated_read
on public.programs for select to authenticated
using (true);

create policy programs_admin_write
on public.programs for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy teacher_assignments_read
on public.teacher_assignments for select to authenticated
using (
  public.current_user_role() = 'admin'
  or teacher_id in (
    select teacher.id
    from public.teachers as teacher
    where teacher.user_id = auth.uid()
  )
);

create policy teacher_assignments_admin_write
on public.teacher_assignments for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

grant select, insert, update, delete on public.programs to authenticated;
grant select, insert, update, delete on public.teacher_assignments to authenticated;
grant usage, select on sequence public.programs_id_seq to authenticated;
grant usage, select on sequence public.teacher_assignments_id_seq to authenticated;
