-- P05 expansion: subject confirmations never rewrite daily RFID evidence.
begin;

create table if not exists public.subject_schedules (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers(id),
  course_id bigint not null,
  program_id bigint not null,
  year_level text not null,
  section text not null,
  campus text not null,
  day_of_week smallint not null check (day_of_week between 0 and 6),
  time_start time not null,
  time_end time not null,
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  foreign key (course_id, program_id) references public.courses(id, program_id),
  check (time_end > time_start),
  check (btrim(year_level) <> '' and btrim(section) <> '' and btrim(campus) <> '')
);
create unique index if not exists subject_schedule_slot_unique
  on public.subject_schedules(course_id, program_id, year_level, section, campus, day_of_week, time_start)
  where status = 'active';

create table if not exists public.subject_attendance (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.subject_schedules(id),
  student_id bigint not null references public.students(id),
  teacher_id bigint not null references public.teachers(id),
  course_id bigint not null references public.courses(id),
  program_id bigint not null references public.programs(id),
  attendance_date date not null,
  attendance_status text not null check (attendance_status in ('Present', 'Absent')),
  -- These are scheduled times, never physical arrival/departure times.
  time_start time not null,
  time_end time not null,
  student_number text not null,
  student_name text not null,
  teacher_name text not null,
  course_code text not null,
  course_name text not null,
  program_code text not null,
  year_level text not null,
  section text not null,
  campus text not null,
  confirmed_by uuid not null references public.users(id),
  confirmed_at timestamptz not null default clock_timestamp(),
  unique (schedule_id, attendance_date, student_id)
);
create index if not exists subject_attendance_date_idx on public.subject_attendance(attendance_date, id);
create index if not exists subject_attendance_student_idx on public.subject_attendance(student_id, attendance_date);
-- Retiring/recreating the same schedule cannot duplicate an already confirmed slot.
create unique index if not exists subject_attendance_session_unique on public.subject_attendance
  (student_id, attendance_date, course_id, program_id, year_level, section, campus, time_start);

-- Check subject ownership as well as student/class ownership. Changing an
-- assignment does not delete the immutable schedule or old confirmations.
create or replace function public.teacher_owns_subject(
  p_teacher bigint, p_course bigint, p_program bigint, p_year text, p_section text, p_campus text
) returns boolean language sql stable security definer set search_path = '' as $$
  select coalesce(public.current_user_role() = 'teacher', false) and exists (
    select 1 from public.teachers t
    join public.teacher_assignments a on a.teacher_id = t.id
    where t.id = p_teacher and t.user_id = auth.uid() and t.status = 'active'
      and a.status = 'active' and a.course_id = p_course and a.program_id = p_program
      and (a.year_level is null or a.year_level = p_year)
      and (a.section is null or a.section = p_section)
      and (a.campus is null or a.campus = p_campus)
  )
$$;

alter table public.subject_schedules enable row level security;
alter table public.subject_attendance enable row level security;
drop policy if exists subject_schedules_read on public.subject_schedules;
create policy subject_schedules_read on public.subject_schedules for select to authenticated using (
  public.current_user_role() = 'admin'
  or public.teacher_owns_subject(teacher_id, course_id, program_id, year_level, section, campus)
  or exists (select 1 from public.students s where s.id = public.current_student_id()
    and s.program_id = subject_schedules.program_id and s.year_level = subject_schedules.year_level
    and s.section = subject_schedules.section and s.campus = subject_schedules.campus)
);
drop policy if exists subject_attendance_read on public.subject_attendance;
create policy subject_attendance_read on public.subject_attendance for select to authenticated using (
  public.current_user_role() = 'admin'
  or student_id = public.current_student_id()
  or (public.teacher_can_access_student(student_id)
    and public.teacher_owns_subject(teacher_id, course_id, program_id, year_level, section, campus))
);
-- Mutation is through checked RPCs only, including for admins.
revoke all on public.subject_schedules, public.subject_attendance from authenticated;
grant select on public.subject_schedules, public.subject_attendance to authenticated;

create or replace function public.create_subject_schedule(
  p_assignment_id bigint, p_day integer, p_start time, p_end time
) returns bigint language plpgsql security definer set search_path = '' as $$
declare a public.teacher_assignments; result bigint;
begin
  if public.current_user_role() is distinct from 'admin' then
    raise exception 'Only an active administrator can configure subject schedules.' using errcode = '42501';
  end if;
  select * into a from public.teacher_assignments where id = p_assignment_id and status = 'active' for share;
  if not found or not exists (select 1 from public.teachers where id = a.teacher_id and status = 'active') then
    raise exception 'Select an active teaching assignment.';
  end if;
  if a.year_level is distinct from '2nd Year' or a.section is null or a.section not in
    ('21001','21002','21003','21004','21005','21006','21007','21008','21009','21010')
    or a.campus is null or a.campus not in ('Main Campus','MV Campus','Bulacan Campus')
    or not exists(select 1 from public.programs where id = a.program_id and upper(program_code) = 'BSIT' and status = 'active')
    or not exists(select 1 from public.courses where id = a.course_id and program_id = a.program_id) then
    raise exception 'Use an active BSIT pilot assignment with an explicit year, section and campus.';
  end if;
  if p_day is null or p_day not between 0 and 6 or p_start is null or p_end is null or p_end <= p_start then
    raise exception 'Choose a weekday and an end time after the start time.';
  end if;
  insert into public.subject_schedules(teacher_id, course_id, program_id, year_level, section, campus, day_of_week, time_start, time_end)
    values(a.teacher_id, a.course_id, a.program_id, a.year_level, a.section, a.campus, p_day, p_start, p_end)
    returning id into result;
  return result;
end $$;

create or replace function public.retire_subject_schedule(p_id bigint)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if public.current_user_role() is distinct from 'admin' then
    raise exception 'Only an active administrator can retire subject schedules.' using errcode = '42501';
  end if;
  update public.subject_schedules set status = 'archived' where id = p_id;
  if not found then raise exception 'Subject schedule not found.'; end if;
end $$;

create or replace function public.confirm_subject_attendance(
  p_schedule_id bigint, p_date date, p_student_id bigint, p_status text,
  p_expected_confirmed_at timestamptz default null
) returns bigint language plpgsql security definer set search_path = '' as $$
declare sch public.subject_schedules; stu public.students; old public.subject_attendance; result bigint;
begin
  if public.current_user_role() is distinct from 'teacher' then
    raise exception 'Only the assigned active teacher can confirm subject attendance.' using errcode = '42501';
  end if;
  select * into sch from public.subject_schedules where id = p_schedule_id for share;
  if not found or sch.status <> 'active' or not public.teacher_owns_subject(
    sch.teacher_id, sch.course_id, sch.program_id, sch.year_level, sch.section, sch.campus) then
    raise exception 'This subject schedule is not an active assignment for your account.' using errcode = '42501';
  end if;
  if p_date is null or p_date > (now() at time zone 'Asia/Manila')::date
    or extract(dow from p_date)::integer <> sch.day_of_week then
    raise exception 'Choose a non-future date on this subject schedule''s weekday.';
  end if;
  if p_status is null or p_status not in ('Present', 'Absent') then
    raise exception 'Confirm Present or Absent.';
  end if;
  select * into stu from public.students where id = p_student_id for share;
  if not found or stu.status <> 'active' or not public.teacher_can_access_student(stu.id)
    or stu.program_id <> sch.program_id or stu.year_level <> sch.year_level
    or stu.section <> sch.section or stu.campus <> sch.campus then
    raise exception 'Student is outside this subject''s active class.' using errcode = '42501';
  end if;
  -- Serialize concurrent first confirmations and reject stale browser edits.
  perform pg_advisory_xact_lock(hashtextextended(p_schedule_id::text || ':' || p_date::text || ':' || p_student_id::text, 0));
  select * into old from public.subject_attendance
    where schedule_id = p_schedule_id and attendance_date = p_date and student_id = p_student_id for update;
  if found then
    if old.attendance_status = p_status then return old.id; end if;
    if p_expected_confirmed_at is distinct from old.confirmed_at then
      raise exception 'Attendance changed since this page was loaded. Refresh before correcting it.' using errcode = '40001';
    end if;
    update public.subject_attendance set attendance_status = p_status, confirmed_by = auth.uid(), confirmed_at = clock_timestamp()
      where id = old.id;
    return old.id;
  end if;
  if p_expected_confirmed_at is not null then raise exception 'Refresh this session before confirming attendance.'; end if;
  insert into public.subject_attendance(schedule_id, student_id, teacher_id, course_id, program_id,
    attendance_date, attendance_status, time_start, time_end, student_number, student_name, teacher_name,
    course_code, course_name, program_code, year_level, section, campus, confirmed_by)
  select sch.id, stu.id, sch.teacher_id, sch.course_id, sch.program_id, p_date, p_status,
    sch.time_start, sch.time_end, stu.student_id, stu.full_name, t.full_name, c.course_code, c.course_name,
    p.program_code, sch.year_level, sch.section, sch.campus, auth.uid()
  from public.teachers t, public.courses c, public.programs p
  where t.id = sch.teacher_id and c.id = sch.course_id and p.id = sch.program_id
  returning id into result;
  return result;
end $$;

revoke all on function public.teacher_owns_subject(bigint,bigint,bigint,text,text,text) from public;
revoke all on function public.create_subject_schedule(bigint,integer,time,time) from public;
revoke all on function public.retire_subject_schedule(bigint) from public;
revoke all on function public.confirm_subject_attendance(bigint,date,bigint,text,timestamptz) from public;
grant execute on function public.teacher_owns_subject(bigint,bigint,bigint,text,text,text) to authenticated;
grant execute on function public.create_subject_schedule(bigint,integer,time,time) to authenticated;
grant execute on function public.retire_subject_schedule(bigint) to authenticated;
grant execute on function public.confirm_subject_attendance(bigint,date,bigint,text,timestamptz) to authenticated;

do $$ begin
  if exists(select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists(select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'subject_attendance') then
      alter publication supabase_realtime add table public.subject_attendance;
    end if;
    if not exists(select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'subject_schedules') then
      alter publication supabase_realtime add table public.subject_schedules;
    end if;
  end if;
end $$;
commit;
