-- Late Attendance Ruling schedules.
-- BSIT 2nd Year pilot: sections 21001-21005 morning (06:00), 21006-21010
-- afternoon (13:00), Philippines Time. A null campus means the row applies to
-- every campus. Sections without a row are never flagged Late.

create table public.class_schedules (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.programs (id),
  year_level text not null,
  section text not null,
  campus text,
  day_of_week smallint not null,
  time_start time not null,
  grace_minutes integer not null default 15,
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint class_schedules_year_level_not_blank check (btrim(year_level) <> ''),
  constraint class_schedules_section_not_blank check (btrim(section) <> ''),
  constraint class_schedules_campus_not_blank
    check (campus is null or btrim(campus) <> ''),
  constraint class_schedules_day_range check (day_of_week between 0 and 6),
  constraint class_schedules_grace_non_negative check (grace_minutes >= 0),
  constraint class_schedules_unique
    unique nulls not distinct
      (program_id, year_level, section, campus, day_of_week)
);

create index class_schedules_lookup_idx
  on public.class_schedules (program_id, year_level, section);

create trigger class_schedules_set_updated_at
before update on public.class_schedules
for each row execute function public.set_updated_at();

alter table public.class_schedules enable row level security;

create policy class_schedules_admin_all
on public.class_schedules for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create policy class_schedules_teacher_read
on public.class_schedules for select to authenticated
using (
  exists (
    select 1
    from public.teacher_assignments as assignment
    join public.teachers as teacher on teacher.id = assignment.teacher_id
    where assignment.program_id = class_schedules.program_id
      and (assignment.year_level is null or assignment.year_level = class_schedules.year_level)
      and (assignment.section is null or assignment.section = class_schedules.section)
      and (class_schedules.campus is null or assignment.campus is null or assignment.campus = class_schedules.campus)
      and teacher.user_id = auth.uid()
      and teacher.status = 'active'
      and assignment.status = 'active'
      and class_schedules.status = 'active'
  )
);

grant select, insert, update, delete on public.class_schedules to authenticated;
grant usage, select on sequence public.class_schedules_id_seq to authenticated;

-- Seed BSIT 2nd Year pilot rows, Monday-Friday.
do $$
declare
  bsit_id bigint;
  sec text;
  start_time time;
  dow smallint;
begin
  insert into public.programs (program_code, program_name)
  values ('BSIT', 'BS Information Technology')
  on conflict do nothing;

  select id into bsit_id
  from public.programs
  where upper(program_code) = 'BSIT';

  for sec in
    select unnest(array['21001', '21002', '21003', '21004', '21005',
                         '21006', '21007', '21008', '21009', '21010'])
  loop
    if sec in ('21001', '21002', '21003', '21004', '21005') then
      start_time := '06:00'::time;
    else
      start_time := '13:00'::time;
    end if;

    for dow in 1..5 loop
      insert into public.class_schedules
        (program_id, year_level, section, campus, day_of_week, time_start)
      values
        (bsit_id, '2nd Year', sec, null, dow, start_time)
      on conflict on constraint class_schedules_unique do nothing;
    end loop;
  end loop;
end
$$;
