-- Academic Setup catalog. Subjects gain an archive status, and one reference
-- table supplies the year level, section, and campus pickers. Additive and
-- idempotent: student, assignment, schedule, and attendance text columns stay
-- as they are, with no foreign keys to the new table.
begin;

-- Subjects are archived, never deleted: assignments, schedules, and attendance
-- snapshots reference them.
alter table public.courses
  add column if not exists status public.account_status not null default 'active';

create table if not exists public.academic_sections (
  id bigint generated by default as identity primary key,
  program_id bigint not null references public.programs (id),
  year_level text not null,
  section_code text not null,
  campus text not null,
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint academic_sections_year_level_not_blank check (btrim(year_level) <> ''),
  constraint academic_sections_section_code_not_blank check (btrim(section_code) <> ''),
  constraint academic_sections_campus_not_blank check (btrim(campus) <> '')
);

create unique index if not exists academic_sections_grouping_unique_idx
  on public.academic_sections (program_id, year_level, upper(section_code), campus);

drop trigger if exists academic_sections_set_updated_at on public.academic_sections;
create trigger academic_sections_set_updated_at
before update on public.academic_sections
for each row execute function public.set_updated_at();

-- Seed the pilot scope (PILOT_SECTIONS x PILOT_CAMPUSES), then every grouping
-- already in use, so no existing placement loses its picker option.
insert into public.academic_sections (program_id, year_level, section_code, campus)
select program.id, '2nd Year', section.code, campus.name
from public.programs as program
cross join unnest(array[
  '21001', '21002', '21003', '21004', '21005',
  '21006', '21007', '21008', '21009', '21010'
]) as section (code)
cross join unnest(array['Main Campus', 'MV Campus', 'Bulacan Campus']) as campus (name)
where upper(btrim(program.program_code)) = 'BSIT'
on conflict do nothing;

insert into public.academic_sections (program_id, year_level, section_code, campus)
select distinct used.program_id, btrim(used.year_level), btrim(used.section), btrim(used.campus)
from (
  select program_id, year_level, section, campus from public.students
  union all
  select program_id, year_level, section, campus from public.subject_schedules
  union all
  select program_id, year_level, section, campus from public.teacher_assignments
) as used
where btrim(coalesce(used.year_level, '')) <> ''
  and btrim(coalesce(used.section, '')) <> ''
  and btrim(coalesce(used.campus, '')) <> ''
on conflict do nothing;

alter table public.academic_sections enable row level security;

drop policy if exists academic_sections_authenticated_read on public.academic_sections;
create policy academic_sections_authenticated_read
on public.academic_sections for select to authenticated
using (true);

drop policy if exists academic_sections_admin_write on public.academic_sections;
create policy academic_sections_admin_write
on public.academic_sections for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

-- The same restrictive gates that later migrations placed on programs.
drop policy if exists active_account_required on public.academic_sections;
create policy active_account_required on public.academic_sections as restrictive
  for all to authenticated
  using ((select public.current_user_role()) is not null)
  with check ((select public.current_user_role()) is not null);
do $$ begin
  if to_regprocedure('public.has_verified_email_session()') is not null then
    execute 'drop policy if exists email_verification_required on public.academic_sections';
    execute 'create policy email_verification_required on public.academic_sections as restrictive for all to authenticated using ((select public.has_verified_email_session())) with check ((select public.has_verified_email_session()))';
  end if;
end $$;

grant select, insert, update, delete on public.academic_sections to authenticated;
grant usage, select on sequence public.academic_sections_id_seq to authenticated;

-- Audit trail and live refresh, when those migrations are installed.
do $$ begin
  if to_regprocedure('public.audit_record_change()') is not null then
    execute 'drop trigger if exists audit_record_change on public.academic_sections';
    execute 'create trigger audit_record_change after insert or update or delete on public.academic_sections for each row execute function public.audit_record_change()';
  end if;
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime'
      and schemaname = 'public' and tablename = 'academic_sections') then
    alter publication supabase_realtime add table public.academic_sections;
  end if;
end $$;

notify pgrst, 'reload schema';
commit;
